export const routes = [
  {
    path: "/",
    name: "Dashboard",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-home"></i>,
  },
  {
    path: "/bookings",
    name: "Bookings",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-clipboard-list"></i>,
  },
  {
    path: "/clinics",
    name: "Clinics",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-hospital"></i>,
  },
  {
    path: "/customers",
    name: "Customers",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-user-friends"></i>,
  },
  {
    path: "/services",
    name: "Services",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-tools"></i>,
  },
  {
    path: "/feedbacks",
    name: "Feedbacks",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-comment-alt"></i>,
  },
  {
    path: "/iam",
    name: "IAM",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-users-cog"></i>,
  },
  {
    path: "/settings",
    name: "Settings",
    showOnSide: true,
    protected: true,
    icon: <i className="fas fa-cog"></i>,
  },
  // {
  //   path: "/auth",
  //   name: "Auth",
  //   showOnSide: false,
  //   protected: false,
  // },
];
